server:
  port: 8080
  address: 0.0.0.0
spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:src/main/resources/static/assets/
      cache:
        period: 3600

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatroom?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456

  # Kafka配置
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: chat-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  # MyBatis配置
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # WebSocket配置
  websocket:
    allowed-origins: "*"

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT配置
jwt:
  secret: "K8wdfUjmn5PqRS7VYzXECtGH2bNMkL4p9aDeWcJvAhQyBx3FuZnTR6gKs4wVfUjmn5PqRS7VYzXECtGH2bNMkL4p9aDeWcJvAhQyBx3FuZnTR6gK"
  expiration: 86400000  # 24小时，单位：毫秒

# 文件上传路径配置
upload:
  path: ${user.dir}/src/main/resources/static/assets/useravatar/

# 日志配置
logging:
  level:
    root: INFO
    top.hujiazheng: DEBUG